name: package_firebase
description: "A new Flutter package project."
version: 0.0.1
#homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  firebase_crashlytics: ^3.4.19
  flutter_local_notifications: ^17.0.0
  firebase_remote_config: ^4.3.18
  firebase_storage: ^11.6.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
