name: package_firebase
description: "A new Flutter package project."
version: 0.0.3
#homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  firebase_crashlytics: ^4.0.4
  flutter_local_notifications: ^17.2.2
  firebase_remote_config: ^5.0.4
  firebase_storage: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
