name: package_firebase
description: "A new Flutter package project."
version: 0.0.4
#homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  firebase_crashlytics: ^4.1.5
  flutter_local_notifications: ^18.0.1
  firebase_remote_config: ^5.1.5
  firebase_storage: ^12.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


#flutter:
